### ISSUE TITLE
ValueError: 'bg_value' should be a list of length 'n_channels'. Got [4.0] for n_channels=2

### ISSUE THREAD

**Issue by suyouooooo** [perslev/MultiPlanarUNet#14]
Hello:
  I got the error"ValueError: 'bg_value' should be a list of length 'n_channels'. Got [4.0] for n_channels=2", so I wonder the meaning of 'bg_value'. 
  I used the task05 prostate dataset, and I followed the instructions in 'readme.md'. I wonder how to fix the problem?

**Comment by perslev** [comment]
Hi,

Sorry I completely missed this issue. Did you ever solve this problem?

Cheers,
Mathias
