### ISSUE TITLE
Input volume is sampled on 2D 

### ISSUE THREAD

**Issue by hilmicanguven** [perslev/MultiPlanarUNet#17]
Sir, great study and I want to say thank you. but I have one issue?

Could you show where do you slice your input volume image (which code or function in the repository) into 2D images exactly?

**Comment by perslev** [comment]
Hi, and thanks!

This is handled by the IsotrophicLiveViewSequence2D class in:
https://github.com/perslev/MultiPlanarUNet/blob/master/mpunet/sequences/isotrophic_live_view_sequence_2d.py#L6

More specifically, have a look at this method:
https://github.com/perslev/MultiPlanarUNet/blob/master/mpunet/sequences/isotrophic_live_view_sequence_2d.py#L119

It references an 'interpolator' object, which you can find here:
https://github.com/perslev/MultiPlanarUNet/blob/master/mpunet/interpolation/view_interpolator.py#L17

Hope this helps.

Cheers,
Mathias

**Comment by hilmicanguven** [comment]
Thank you for your detailed response Sir. best regards.
