### ISSUE TITLE
Does MPU have to install "tensorflow-gpu==2.3.2"? The readme file says that GPU is not required.

### ISSUE THREAD

**Issue by TL730** [perslev/MultiPlanarUNet#19]
Does MPU have to install "tensorflow-gpu==2.3.2"? The readme file says that GPU is not required.

**Comment by perslev** [comment]
Hi, no you don't need to use a GPU. Replace the `tensorflow-gpu==2.3.2` with `tensorflow==2.3.2` in the requirements.txt file and run `mp train --num_GPUs=0`. Note, however, that depending on the size of your images it might be very slow to run training without a GPU.
