### ISSUE TITLE
Why do we need 'predict_single' in predict.py?

### ISSUE THREAD

**Issue by Paddy-Xu** [perslev/MultiPlanarUNet#21]
Hi Mathias, 

I think it's a really cool work, both the ideas and codes. I just have one confusion about a small part of the codes in predict.py.

in the `run_predictions_and_eval` function, before iterating images from `image_pair_dict`, why do we need to run `predict_single` over `image_pair_loader.images[0]`, at line 425? That just seems to be a useless step because you iterate over all images in the `for` loop right after it?

Thanks in advance!

**Comment by perslev** [comment]
Hi,

Oh wow, good catch! Thank you for spotting this. I think this code made it into the repo by accident. I will remove it asap.

Cheers,
Mathias

**Comment by perslev** [comment]
Fixed in 4530159d5b95edb38def6814527a057bbffdd884.
