### ISSUE TITLE
What is real_space_span?

### ISSUE THREAD

**Issue by YifengSunNJ** [perslev/MultiPlanarUNet#23]
Hi,

The code works very well, and I could train my custom dataset with very good performance. I also think the paper is intuitively easy to read. But I just don't quite understand what the value of real_space_span indicates in train_hparams.yaml. e.g. How is it calculated from the image data? Or is it just set up with fixed number?

Thanks!

**Comment by perslev** [comment]
Hi,

The `real_space_span` is the number of millimetres of distance in the scanner/"real" space that the sampled images should span. I.e., if `real_space_span = 100` and the image dimension is `dim = 200`, then 200 pixels are to be sampled to span 100 millimetres of space giving a pixel size of 0.5mm.

It is heuristically calculated as the 75th percentile of sizes of all training images (i.e., the extent of the images in scanner space). See:

https://github.com/perslev/MultiPlanarUNet/blob/73b3f9e59484c9122ff3781062ee1634965f91e9/mpunet/image/auditor.py#L108

Hope this clarifies,
Mathias
