### ISSUE TITLE
xla_gup not compatible to newest tensorflow version

### ISSUE THREAD

**Issue by LongxiZhou** [perslev/MultiPlanarUNet#9]
the error is:
ValueError: To call multi_gpu_modelwithgpus=2, we expect the following devices to be available: ['/cpu:0', '/gpu:0', '/gpu:1']. However this machine only has: ['/cpu:0', '/xla_gpu:0', '/xla_gpu:1', '/xla_cpu:0']. Try reducing gpus.

Others on github says it is a bug of newest tf, and the flowing version will solve the above issue:
Tensorflow 2.0
CUDA 10.0
cuDNN 7.6.4 (described as dedicated for CUDA 10.0)

However, when I degrade the tf version to 2.0, the issue still exists.
Could you make you model running on these version?
Could you tell me which version should I use or update the requirements?

**Comment by perslev** [comment]
Hi,

This is likely because the mpunet still relies on the old tf.keras multi_gpu_model function for distributing models across multiple GPUs. I will soon (within the next few days) update to use the proper TensorFlow 2 approach (tf.distribute.MirroredStrategy), which I believe will fix your error.

**Comment by perslev** [comment]
Hi,
Could you try and checkout on branch 'v.0.2.5' and see if it that works for you?
